# Generated by Django 5.1.6 on 2025-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
